### PR TITLE
ci: enable license checking

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/workflows/issues/49

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Package "@assemblyscript/loader@0.10.1" is licensed under "Apache-2.0" which is not permitted by the --onlyAllow flag. Exiting.

https://github.com/fastify/workflows/pull/50

**Comment by Fdawgs** [comment]
@Uzlopak, GitHub Actions seem a bit sluggish today and there's been a few just timing out, not too sure if there's an issue with them. Will try rerunning these tomorrow.

**Comment by Eomm** [comment]
New error

```
Package "hdr-histogram-js@2.0.3" is licensed under "BSD*" which is not permitted by the --onlyAllow flag. Exiting.
```

**Comment by Fdawgs** [comment]
> New error
> 
> 
> 
> ```
> 
> Package "hdr-histogram-js@2.0.3" is licensed under "BSD*" which is not permitted by the --onlyAllow flag. Exiting.
> 
> ```

Will review tomorrow, and most likely raise an issue in their repo to fix their license identifier

**Comment by Uzlopak** [comment]
https://github.com/HdrHistogram/HdrHistogramJS/pull/46

**Comment by Uzlopak** [comment]
@Fdawgs 

We could add BSD* as additional license and make it merge ready.

**Comment by Fdawgs** [comment]
> @Fdawgs
> 
> We could add BSD* as additional license and make it merge ready.

Sure, will update and merge, and keep an eye on https://github.com/HdrHistogram/HdrHistogramJS/pull/46

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
